### ISSUE TITLE
doesn't work with patch 1.61 anymore

### ISSUE THREAD

**Issue by mbunkus** [jackhumbert/cyberpunk2077-input-loader#4]
Love the mod. Thanks for your work!

This mod used to work just fine up to & including patch 1.6 for quite a while. After today's patch 1.61 & updating a lot of other mods, the game simply doesn't start anymore if `input_loader` 0.0.6 is activated in Vortex. The symptom is: launching the game, observing that the exe pops up in task manager for a second or two & then vanishes. There's no switching to the game graphics, there's no error message, nothing; the process just dies quietly.

I'll gladly provide more information if required; just tell me what & where to find it. Thanks!

**Comment by ghost** [comment]
Same experience for me here!

**Comment by VulumeCode** [comment]
As a temporary fix you can use the `inputContexts.xml` files `inputUserMappings.xml` generated by Input Loader, they should still be in the `cache` folder. 

Backup the ones that come with the game, and put the generated files in their place. Also delete input_loader.dll so the game can boot. Your custom controls are now available without input loader.

Patch 1.61 does not modify these files so you're not missing out on any updates this way. 

Remember to revert this when installing the updated Input Loader that hopefully comes soon.

**Comment by mbunkus** [comment]
The newly released version 0.0.7 seems to work fien with patch 1.61. Thanks!
